#!/bin/bash



# -------- DECLARATIONS --------

#current execution directory
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)

#paths
OUT=$pCXD/out
TMP=$OUT/tmp
APP=$OUT/app





# -------- EXECUTION --------

#create output directory
rm -rf $OUT
mkdir  $OUT $TMP $APP

#dependencies
cd $TMP
gcc -Wall -O2 -c $pCXD/src/graphics/S2DE.c -I/usr/include/GL
gcc -Wall -O2 -c $pCXD/src/graphics/displayTools.c
gcc -Wall -O2 -c $pCXD/src/VisualLinux.c
gcc -Wall -O2 -c $pCXD/src/UC2kHC.c

#executables
gcc -Wall -o $APP/VisualLinux $TMP/VisualLinux.o $TMP/displayTools.o $TMP/S2DE.o -lm -lglut -lGL -lX11
gcc -Wall -o $APP/UC2kHC      $TMP/UC2kHC.o
